# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  pkgs,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/hardware/cpu/intel-npu.nix")
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    kernelModules = [ "kvm-intel" ];
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "thunderbolt"
        "nvme"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [ "dm-snapshot" ];
      luks.devices."asanagi" = {
        device = "/dev/disk/by-uuid/93522ee3-9f94-4af4-9073-5b086c9c0dcd";
        preLVM = true;
        allowDiscards = true;
      };
    };
    extraModulePackages = [ ];
  };

  fileSystems = {
    "/" = {
      device = "none";
      fsType = "tmpfs";
      options = [
        "defaults"
        "size=10%"
        "mode=755"
      ];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/0BFD-C0A3";
      fsType = "vfat";
      options = [
        "fmask=0022"
        "dmask=0022"
      ];
    };

    "/nix" = {
      device = "/dev/mapper/asanagi-root";
      fsType = "btrfs";
      options = [
        "subvol=@nix"
        "rw"
        "noatime"
        "compress-force=zstd:7"
        "ssd"
        "space_cache=v2"
        "autodefrag"
      ];
    };

    "/nix/persist" = {
      device = "/dev/mapper/asanagi-root";
      fsType = "btrfs";
      options = [
        "subvol=@persist"
        "rw"
        "noatime"
        "compress-force=zstd:7"
        "ssd"
        "space_cache=v2"
        "autodefrag"
      ];
      neededForBoot = true;
    };

    "/home" = {
      device = "/dev/mapper/asanagi-root";
      fsType = "btrfs";
      options = [
        "subvol=@home"
        "rw"
        "noatime"
        "compress-force=zstd:7"
        "ssd"
        "space_cache=v2"
        "autodefrag"
      ];
    };

    "/home/.snapshots" = {
      device = "/dev/mapper/asanagi-root";
      fsType = "btrfs";
      options = [
        "subvol=@snapshots"
        "rw"
        "noatime"
        "compress-force=zstd:7"
        "ssd"
        "space_cache=v2"
        "autodefrag"
      ];
    };

    "/tmp" = {
      device = "none";
      fsType = "tmpfs";
      options = [
        "rw"
        "nr_inodes=10k"
        "noexec"
        "nodev"
        "nosuid"
        "size=50%"
      ];
    };
  };

  #swapDevices = [ { device = "/dev/mapper/asanagi-swap"; } ];

  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    extraPackages = with pkgs; [
      intel-compute-runtime
      intel-media-driver
      vpl-gpu-rt
    ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware.enableAllFirmware = true;
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = true;
}
