[anthropics-skills]
source = "github"
github = "anthropics/skills"

[eisvogel-template]
source = "github"
github = "Wandmalfarbe/pandoc-latex-template"
use_latest_release = true
prefix = "v"

[humanizer]
source = "github"
github = "blader/humanizer"

[humanizer-zh]
source = "github"
github = "op7418/Humanizer-zh"

[spotify-adblock]
source = "github"
github = "abba23/spotify-adblock"
