# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    kernelModules = [ ];
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ahci"
        "nvme"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [ "dm-snapshot" ];
      luks.devices."amagi" = {
        device = "/dev/disk/by-uuid/242ecf80-4014-4dc8-9fe2-baa920cd37fc";
        preLVM = true;
        allowDiscards = true;
      };
    };
    extraModulePackages = [ ];
  };

  fileSystems = {
    "/" = {
      device = "none";
      fsType = "tmpfs";
      options = [
        "defaults"
        "size=10%"
        "mode=755"
      ];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/B36A-AE70";
      fsType = "vfat";
      options = [
        "fmask=0022"
        "dmask=0022"
      ];
    };

    "/nix" = {
      device = "/dev/mapper/amagi-root";
      fsType = "btrfs";
      options = [
        "subvol=@nix"
        "rw"
        "noatime"
        "compress-force=zstd:7"
        "ssd"
        "space_cache=v2"
        "autodefrag"
      ];
    };

    "/nix/persist" = {
      device = "/dev/mapper/amagi-root";
      fsType = "btrfs";
      options = [
        "subvol=@persist"
        "rw"
        "noatime"
        "compress-force=zstd:7"
        "ssd"
        "space_cache=v2"
        "autodefrag"
      ];
      neededForBoot = true;
    };

    "/home" = {
      device = "/dev/mapper/amagi-root";
      fsType = "btrfs";
      options = [
        "subvol=@home"
        "rw"
        "noatime"
        "compress-force=zstd:7"
        "ssd"
        "space_cache=v2"
        "autodefrag"
      ];
    };

    "/home/.snapshots" = {
      device = "/dev/mapper/amagi-root";
      fsType = "btrfs";
      options = [
        "subvol=@snapshots"
        "rw"
        "noatime"
        "compress-force=zstd:7"
        "ssd"
        "space_cache=v2"
        "autodefrag"
      ];
    };

    "/tmp" = {
      device = "none";
      fsType = "tmpfs";
      options = [
        "rw"
        "nr_inodes=10k"
        "noexec"
        "nodev"
        "nosuid"
        "size=50%"
      ];
    };
  };

  swapDevices = [ { device = "/dev/mapper/amagi-swap"; } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware.enableAllFirmware = true;
  hardware.cpu.amd.updateMicrocode = true;
}
